# Vibes
title: nocc nocc blog
description: having fun, have fun.

# Theme
remote_theme: Gaohaoyang/gaohaoyang.github.io

# Markdown / Rendering
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  auto_ids: true
  entity_output: as_char
  toc_levels: [1, 2, 3, 4, 5, 6]
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  hard_wrap: false
  footnote_nr: 1

# Permalinks & structure
permalink: date
paginate_path: /page:num
timezone: America/Vancouver

# Include / Exclude
include: [".htaccess"]
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/

# Liquid
liquid:
  error_mode: warn
